### ISSUE TITLE
老铁,请问安装数据库呢.

### ISSUE THREAD

**Issue by Y-A-K-E** [12tla/twelvet#1]
打开后台入口love.php也报错

致命错误: Call to undefined function captcha_src()

**Comment by twelvet-s** [comment]
还未发布，如有需要可以联系QQ:2471835953晚点打包给你


 
---原始邮件---
发件人: "Y.A.K.E"<notifications@github.com&gt;
发送时间: 2019年11月19日 13:28:33
收件人: "twelvet-s/twelvet-php"<twelvet-php@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [twelvet-s/twelvet-php] 老铁,请问安装数据库呢. (#1)



打开后台入口love.php也报错
 
致命错误: Call to undefined function captcha_src()

**Comment by Y-A-K-E** [comment]
我QQ好久没登陆忘记密码登不上了.

能不能发我邮箱
y@yge.me

非常感谢!!!

**Comment by Y-A-K-E** [comment]
已经收到!完美运行.感谢.
研究学习TP中.

**Comment by h7ml** [comment]
老铁，请问安装数据库呢
